apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc-allow-root
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostPorts: true
allowHostPID: true
allowHostIPC: true
allowHostDirVolumePlugin: true
allowHostNamespace: false
allowedUnsafeSysctls: null
defaultAddCapabilities: null
requiredDropCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: 10
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:admin
  - system:unauthenticated
  - system:serviceaccount:ai-testpython:default
supplementalGroups:
  type: RunAsAny
volumes:
  - '*'